# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    configs:
        bigEditor:
            toolbar: "full"
        main_config:
            toolbar:
                - {
                      name: "styles",
                      items:
                          [
                              "Bold",
                              "Italic",
                              "Underline",
                              "Strike",
                              "TextColor",
                              "BGColor",
                              "Blockquote",
                              "-",
                              "Link",
                              "-",
                              "RemoveFormat",
                              "-",
                              "NumberedList",
                              "BulletedList",
                              "-",
                              "Outdent",
                              "Indent",
                              "-",
                              "-",
                              "JustifyLeft",
                              "JustifyCenter",
                              "JustifyRight",
                              "JustifyBlock",
                              "-",
                              "Table",
                              "-",
                              "Styles",
                              "Format",
                              "Font",
                              "FontSize",
                              "-",
                              "TextColor",
                              "BgColor",
                          ],
                }
            bottom bar: "none"

